<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <AssemblyName>WebNet.PostgresEmbed.Tests</AssemblyName>
    <PackageId>WebNet.PostgresEmbed.Tests</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebNet.PostgresEmbed\WebNet.PostgresEmbed.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="Xunit.SkippableFact" Version="1.5.23" />
  </ItemGroup>

</Project>
