<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Postgres embedded server equivalent for .Net applications</Description>
    <Copyright>Copyright (C) miserix13</Copyright>
    <AssemblyTitle>WebNet.PostgresEmbed</AssemblyTitle>
    <VersionPrefix>4.1.0</VersionPrefix>
    <Authors>miserix13</Authors>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <AssemblyName>WebNet.PostgresEmbed</AssemblyName>
    <PackageId>WebNet.PostgresEmbed</PackageId>
    <PackageTags>postgres;postgresql;pg;embed;embedded;server;.net 4.6;net 4.6;net46;.net core;net core;netcore;netcore 2.0;netcore rtm</PackageTags>
    <PackageProjectUrl>https://github.com/miserix13/postgresembed</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/mysticmind/mysticmind-postgresembed</RepositoryUrl>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>PostgresEmbed</Title>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <FileVersion>4.2.0.0</FileVersion>
    <Version>4.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Polly.Core" Version="8.7.0" />
    <PackageReference Include="SharpCompress" Version="0.50.4" />
  </ItemGroup>
</Project>
